import 'dart:async';

import 'package:flutter/cupertino.dart';

import 'app-assets.dart';

Future<void> preloadImages() async {
  final List<String> assetPaths = [
    AppAssets.appIcon,
    AppAssets.appLogo,
    AppAssets.roleEllipse,
    AppAssets.customerIcon,
    AppAssets.driverIcon,
    AppAssets.selectRoleIcon,
    AppAssets.sellerIcon,
    AppAssets.signUpEllipse,
    AppAssets.signUpImage,
    AppAssets.emailIcon,
    AppAssets.passwordIcon,
    AppAssets.personIcon,
    AppAssets.forgetPasswordIcon,
    AppAssets.backArrow,
    AppAssets.googleIcon,
    AppAssets.facebookIcon,
    AppAssets.homeSideIcon,
    AppAssets.myProfileSideIcon,
    AppAssets.googleIcon,
    AppAssets.pedingDeliveriesIcon,
    AppAssets.privacyIcon,
    AppAssets.termAndConditionIcon,
    AppAssets.viewHistoryIcon,
    AppAssets.callIcon,
    AppAssets.cartIcon,
    AppAssets.addIcon,
    AppAssets.sendIcon,
    AppAssets.emojiIcon,
    AppAssets.homeBottomIcon,
    AppAssets.messageBottomIcon,
    AppAssets.personBottomIcon,
    AppAssets.toolBottomIcon,
    AppAssets.bellIcon,
    AppAssets.addIconT,
    AppAssets.arrowIcon,
    AppAssets.addProductIcon,
    AppAssets.helpCenterIcon,
    AppAssets.manageReviewsIcon,
    AppAssets.myIncomeIcon,
    AppAssets.orderIcon,
    AppAssets.returnOrderIcon,
    AppAssets.arrowBack,
    AppAssets.shareIcon,
    AppAssets.cancelIcon,
    AppAssets.settingIcon,
    AppAssets.scanIcon,
    AppAssets.selectProductIcon,
    AppAssets.productRemoveIcon,
    AppAssets.productChatIcon,
    AppAssets.starIcon,
    AppAssets.shopHomePageIcon,
    AppAssets.shareShopIcon,
    AppAssets.smileIcon,
    AppAssets.cartBottomIcon,
    AppAssets.categoriesBottomIcon,
    AppAssets.customerHomeBottomIcon,
    AppAssets.profileBottomIcon,
    AppAssets.clothCategory,
    AppAssets.cosmeticsCategory,
    AppAssets.electronicsCategory,
    AppAssets.babyProducts,
    AppAssets.backToSchool,
    AppAssets.clearenseSale,
    AppAssets.hotDeals,
    AppAssets.grabDealRectangle,
    AppAssets.grabDealPicTwo,
    AppAssets.grabDealPic,
    AppAssets.flashIcon,
    AppAssets.masterCardIcon,
    AppAssets.infoIcon,
    AppAssets.cuteryPic,
    AppAssets.oilPic,
    AppAssets.specPic,
    AppAssets.gridIcon,
    AppAssets.flashSaleOrageBg,
    AppAssets.heartIcon,
    AppAssets.productShareIcon,
    AppAssets.productDeliveryIcon,
    AppAssets.productGridIcon,
    AppAssets.warrantyIcon,
    AppAssets.askQuestionIcon,
    AppAssets.productChatIconT,
    AppAssets.halfHeartLeft,
    AppAssets.halfHeartRight,
    AppAssets.crossIcon,
    AppAssets.questionIcon,
    AppAssets.answerIcon,
    AppAssets.commentIcon,
    AppAssets.likeIcon,
    AppAssets.visitStoreImg,
    AppAssets.floatingChatIcon,
    AppAssets.cameraImg,
    AppAssets.ordersChatImg,
    AppAssets.photosImg,
    AppAssets.productChatImg,
    AppAssets.fruitsIcon,
    AppAssets.bakeryDipImg,
    AppAssets.bakeryImg,
    AppAssets.eggFistImg,
    AppAssets.deleteIcon,
    AppAssets.deliveryVehicleIcon,
    AppAssets.shippingVoucherIcon,
    AppAssets.sugudeniCoinIcon,
    AppAssets.voucherIcon,
    AppAssets.paymentCashOnDeliveryIcon,
    AppAssets.clockIcon,
    AppAssets.customerProfileIcon,
    AppAssets.customerDraverIcon,
    AppAssets.progressStepOne,
    AppAssets.progressStepThree,
    AppAssets.progressStepTwo,
    AppAssets.trackingIcon,
    AppAssets.myProductSellerIcon,
    AppAssets.ratingDoneIcon,
    AppAssets.checkIcon,
    AppAssets.accountDeletionIcon,
    AppAssets.passwordEyeIcon,
    AppAssets.tick_icon,

    /// dummy assets
    AppAssets.dummyUserFour,
    AppAssets.dummyUserOne,
    AppAssets.dummyUserThree,
    AppAssets.dummyUserTwo,
    AppAssets.shippedDummy,
    AppAssets.dummyChilliIcon,
    AppAssets.dummyProductFour,
    AppAssets.dummyProductThree,
    AppAssets.dummyProductTwo,
    AppAssets.dummyAddHome,
    AppAssets.dummyShampoo,
    AppAssets.flashSalePicOne,
    AppAssets.flashSalePicThree,
    AppAssets.flashSalePicTwo,
    AppAssets.productDescription,
    AppAssets.dummyGirlShopping,
    AppAssets.storeDummyFour,
    AppAssets.storeDummyOne,
    AppAssets.storeDummyThree,
    AppAssets.storeDummyTwo,

  ];

  await Future.wait(assetPaths.map((path) => loadImage(path)));
}
Future<void> loadImage(String path) {
  final Completer<void> completer = Completer();
  final ImageStream stream = AssetImage(path).resolve(const ImageConfiguration());

  stream.addListener(
    ImageStreamListener(
          (ImageInfo image, bool synchronousCall) {
        completer.complete();
      },
      onError: (dynamic error, StackTrace? stackTrace) {
        completer.completeError(error);
      },
    ),
  );
  return completer.future;
}