// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh_TfPivquJRemEmWsq9_51A00isLDvnU',
    appId: '1:125404866684:android:565066c7c8af8d0d1941f9',
    messagingSenderId: '125404866684',
    projectId: 'sugudeni',
    storageBucket: 'sugudeni.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwg4i7u82idYaVINcjIXrbPkKcs7RaNZs',
    appId: '1:125404866684:ios:3218a6e7975925e31941f9',
    messagingSenderId: '125404866684',
    projectId: 'sugudeni',
    storageBucket: 'sugudeni.firebasestorage.app',
    androidClientId: '125404866684-hvl3sh43l23uep44tau0kpggque024om.apps.googleusercontent.com',
    iosClientId: '125404866684-opcc4nrbcrca01e7en50m586lo0b2j14.apps.googleusercontent.com',
    iosBundleId: 'app.Sugudeni.com',
  );

}